# Usa uma imagem base do Python
FROM python:3.9-slim

# arquivo app.py -(cópia)-> container
COPY app.py /app.py

# Executa o código (como se digitasse "python /app.py" no temrinal. "," = " ")
CMD ["python", "/app.py"]